apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ant
bases:
  - ../../base
images:
  - name: IMAGE_PLACEHOLDER
    newName: $CI_REGISTRY_IMAGE
    newTag: $CI_COMMIT_SHA
configMapGenerator:
  - name: ant-fileserver-config
    literals:
      - LOG_LEVEL=info
replicas:
  - name: ant-fileserver
    count: 2
