apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ant-prod

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - secret.yaml

patches:
  - path: deployment-patch.yaml
images:
  - name: ant-fileserver
    newName: ghcr.io/allie-leth/ant-fileserver
    newTag: latest
configMapGenerator:
  - name: ant-fileserver-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - FLASK_ENV=production
      - STORAGE_ENDPOINT=http://minio.minio.svc.cluster.local:9000
      - STORAGE_BUCKET=ant-fileserver-prod
replicas:
  - name: ant-fileserver
    count: 2
