apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ant
bases:
  - ../../base
images:
  - name: IMAGE_PLACEHOLDER
    newName: ghcr.io/allie-leth/ant-fileserver
    newTag: dev
configMapGenerator:
  - name: ant-fileserver-config
    literals:
      - LOG_LEVEL=debug
