[pytest]
addopts = -ra -m "not integration"
testpaths =
    tests/unit
    tests/api
    tests/integration
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"')
