apiVersion: v1
kind: ServiceAccount
metadata:
  name: ant-fileserver
  labels:
    app: ant-fileserver
    app.kubernetes.io/name: ant-fileserver
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ant-firmware